import { Deal } from '@/types';

export const dealsData: Deal[] = [
  // ─── Lisbon ───────────────────────────────────────────────────────────
  {
    id: 'lisbon-1',
    destination: 'Lisbon',
    country: 'Portugal',
    hotel: 'Hotel Memmo Alfama',
    image: 'https://images.unsplash.com/photo-1548707309-dcebeab9ea9b?w=600&h=400&fit=crop',
    dates: 'May 2–5, 2026',
    nights: 3,
    pricePerPerson: 189,
    originalPrice: 265,
    dealConfidence: 94,
    confidenceRationale: '29% below 90-day average for these dates',
    tags: ['warm', 'food', 'culture', 'riverside', 'historic'],
    highlights: ['Alfama district views', 'Rooftop pool', 'Complimentary pastéis de nata'],
  },
  {
    id: 'lisbon-2',
    destination: 'Lisbon',
    country: 'Portugal',
    hotel: 'Bairro Alto Hotel',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&h=400&fit=crop',
    dates: 'Jun 19–22, 2026',
    nights: 3,
    pricePerPerson: 245,
    originalPrice: 310,
    dealConfidence: 81,
    confidenceRationale: 'Good price — peak season but 21% below average',
    tags: ['warm', 'luxury', 'food', 'culture', 'nightlife'],
    highlights: ['Bairro Alto location', '5-star spa', 'Award-winning restaurant'],
  },
  {
    id: 'lisbon-3',
    destination: 'Lisbon',
    country: 'Portugal',
    hotel: 'LX Boutique Hotel',
    image: 'https://images.unsplash.com/photo-1604928141064-207cea6f571f?w=600&h=400&fit=crop',
    dates: 'Mar 13–16, 2026',
    nights: 3,
    pricePerPerson: 149,
    originalPrice: 199,
    dealConfidence: 89,
    confidenceRationale: '25% below annual average, shoulder season sweet spot',
    tags: ['warm', 'budget', 'food', 'artsy', 'historic'],
    highlights: ['Tagus river views', 'Design-forward rooms', 'LX Factory nearby'],
  },

  // ─── Barcelona ────────────────────────────────────────────────────────
  {
    id: 'barcelona-1',
    destination: 'Barcelona',
    country: 'Spain',
    hotel: 'Hotel Casa Bonay',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&h=400&fit=crop',
    dates: 'Jun 12–15, 2026',
    nights: 3,
    pricePerPerson: 245,
    originalPrice: 340,
    dealConfidence: 87,
    confidenceRationale: '28% below comparable dates last year',
    tags: ['warm', 'food', 'nightlife', 'beach', 'culture'],
    highlights: ['Eixample neighbourhood', 'Craft cocktail bar', 'Gaudi architecture nearby'],
  },
  {
    id: 'barcelona-2',
    destination: 'Barcelona',
    country: 'Spain',
    hotel: 'Hotel Arts Barcelona',
    image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&h=400&fit=crop',
    dates: 'May 8–11, 2026',
    nights: 3,
    pricePerPerson: 359,
    originalPrice: 480,
    dealConfidence: 78,
    confidenceRationale: 'Luxury at 25% off — still premium pricing for peak',
    tags: ['warm', 'luxury', 'beach', 'romantic', 'food'],
    highlights: ['Beachfront 5-star', 'Michelin-starred dining', 'Infinity pool'],
  },
  {
    id: 'barcelona-3',
    destination: 'Barcelona',
    country: 'Spain',
    hotel: 'Hotel Jazz',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
    dates: 'Apr 3–6, 2026',
    nights: 3,
    pricePerPerson: 175,
    originalPrice: 230,
    dealConfidence: 91,
    confidenceRationale: 'Historic low for April — 24% below 2-year average',
    tags: ['warm', 'budget', 'culture', 'food', 'artsy'],
    highlights: ['Raval district', 'Rooftop pool', 'MACBA museum steps away'],
  },

  // ─── Amsterdam ────────────────────────────────────────────────────────
  {
    id: 'amsterdam-1',
    destination: 'Amsterdam',
    country: 'Netherlands',
    hotel: 'Pulitzer Amsterdam',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&h=400&fit=crop',
    dates: 'Apr 10–13, 2026',
    nights: 3,
    pricePerPerson: 275,
    originalPrice: 380,
    dealConfidence: 88,
    confidenceRationale: '28% off during tulip season — exceptional value',
    tags: ['culture', 'food', 'artsy', 'romantic', 'historic'],
    highlights: ['17th-century canal houses', 'Private garden', 'Rijksmuseum nearby'],
  },
  {
    id: 'amsterdam-2',
    destination: 'Amsterdam',
    country: 'Netherlands',
    hotel: 'Hotel V Nesplein',
    image: 'https://images.unsplash.com/photo-1572435555646-7ad9a149ad91?w=600&h=400&fit=crop',
    dates: 'Mar 6–9, 2026',
    nights: 3,
    pricePerPerson: 199,
    originalPrice: 255,
    dealConfidence: 83,
    confidenceRationale: '22% below average for this hotel category',
    tags: ['culture', 'artsy', 'food', 'budget'],
    highlights: ['Central Amsterdam', 'Design boutique', 'Jordaan neighbourhood'],
  },
  {
    id: 'amsterdam-3',
    destination: 'Amsterdam',
    country: 'Netherlands',
    hotel: 'Kimpton De Witt',
    image: 'https://images.unsplash.com/photo-1546636889-ba9fdd63583e?w=600&h=400&fit=crop',
    dates: 'May 22–25, 2026',
    nights: 3,
    pricePerPerson: 229,
    originalPrice: 295,
    dealConfidence: 85,
    confidenceRationale: '22% below 90-day forward average',
    tags: ['culture', 'food', 'nightlife', 'historic', 'artsy'],
    highlights: ['Historic building conversion', 'Award-winning bar', 'Dam Square location'],
  },

  // ─── Rome ─────────────────────────────────────────────────────────────
  {
    id: 'rome-1',
    destination: 'Rome',
    country: 'Italy',
    hotel: 'Hotel de Russie',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&h=400&fit=crop',
    dates: 'Mar 27–30, 2026',
    nights: 3,
    pricePerPerson: 395,
    originalPrice: 540,
    dealConfidence: 90,
    confidenceRationale: '27% off shoulder season — best luxury deal this year',
    tags: ['culture', 'food', 'luxury', 'historic', 'romantic'],
    highlights: ['Steps from Spanish Steps', 'Secret garden', 'Celebrity favourite'],
  },
  {
    id: 'rome-2',
    destination: 'Rome',
    country: 'Italy',
    hotel: 'Residenza Paolo VI',
    image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=600&h=400&fit=crop',
    dates: 'Apr 17–20, 2026',
    nights: 3,
    pricePerPerson: 219,
    originalPrice: 285,
    dealConfidence: 86,
    confidenceRationale: '23% below pre-summer average for central Rome',
    tags: ['culture', 'historic', 'food', 'romantic'],
    highlights: ['Vatican views', 'Terrace breakfast', 'UNESCO World Heritage location'],
  },
  {
    id: 'rome-3',
    destination: 'Rome',
    country: 'Italy',
    hotel: 'Generator Roma',
    image: 'https://images.unsplash.com/photo-1525874684015-58379d421a52?w=600&h=400&fit=crop',
    dates: 'Feb 27 – Mar 2, 2026',
    nights: 3,
    pricePerPerson: 129,
    originalPrice: 165,
    dealConfidence: 92,
    confidenceRationale: '22% below 2-year average — lowest price this winter',
    tags: ['culture', 'historic', 'budget', 'food'],
    highlights: ['Pigneto neighbourhood', 'Social bar and events', 'Authentic local area'],
  },

  // ─── Porto ────────────────────────────────────────────────────────────
  {
    id: 'porto-1',
    destination: 'Porto',
    country: 'Portugal',
    hotel: 'Yeatman Hotel',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&h=400&fit=crop',
    dates: 'May 15–18, 2026',
    nights: 3,
    pricePerPerson: 269,
    originalPrice: 360,
    dealConfidence: 88,
    confidenceRationale: '25% below peak rates — rare availability for this hotel',
    tags: ['warm', 'food', 'wine', 'luxury', 'romantic', 'riverside'],
    highlights: ['Douro Valley views', 'Wine cellar and tasting', 'Michelin-starred kitchen'],
  },
  {
    id: 'porto-2',
    destination: 'Porto',
    country: 'Portugal',
    hotel: 'Flores Village Hotel',
    image: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=600&h=400&fit=crop',
    dates: 'Apr 24–27, 2026',
    nights: 3,
    pricePerPerson: 179,
    originalPrice: 235,
    dealConfidence: 93,
    confidenceRationale: '24% off — historic low for April in Porto',
    tags: ['warm', 'food', 'culture', 'budget', 'historic', 'riverside'],
    highlights: ['Ribeira district', 'Azulejo tile courtyard', 'Steps to port wine lodges'],
  },
  {
    id: 'porto-3',
    destination: 'Porto',
    country: 'Portugal',
    hotel: 'Hotel Infante Sagres',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=600&h=400&fit=crop',
    dates: 'Jun 5–8, 2026',
    nights: 3,
    pricePerPerson: 209,
    originalPrice: 270,
    dealConfidence: 82,
    confidenceRationale: '23% off — good price heading into peak season',
    tags: ['warm', 'food', 'culture', 'historic', 'romantic'],
    highlights: ['Art nouveau palace', 'Central location', 'Rooftop bar'],
  },

  // ─── Prague ───────────────────────────────────────────────────────────
  {
    id: 'prague-1',
    destination: 'Prague',
    country: 'Czech Republic',
    hotel: 'Hotel Josef',
    image: 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=600&h=400&fit=crop',
    dates: 'Mar 20–23, 2026',
    nights: 3,
    pricePerPerson: 155,
    originalPrice: 210,
    dealConfidence: 91,
    confidenceRationale: '26% below annual average — exceptional shoulder season rate',
    tags: ['cold', 'culture', 'architecture', 'budget', 'nightlife', 'historic'],
    highlights: ['Design hotel', 'New Town location', 'Walking distance to Old Town Square'],
  },
  {
    id: 'prague-2',
    destination: 'Prague',
    country: 'Czech Republic',
    hotel: 'Four Seasons Prague',
    image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=600&h=400&fit=crop',
    dates: 'Apr 10–13, 2026',
    nights: 3,
    pricePerPerson: 289,
    originalPrice: 390,
    dealConfidence: 85,
    confidenceRationale: '26% below last year — strong deal for 5-star Prague',
    tags: ['cold', 'culture', 'luxury', 'architecture', 'romantic', 'historic'],
    highlights: ['Vltava river views', 'Michelin-starred spa', 'Charles Bridge steps away'],
  },
  {
    id: 'prague-3',
    destination: 'Prague',
    country: 'Czech Republic',
    hotel: 'Mosaic House',
    image: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=600&h=400&fit=crop',
    dates: 'Feb 20–23, 2026',
    nights: 3,
    pricePerPerson: 119,
    originalPrice: 155,
    dealConfidence: 95,
    confidenceRationale: '23% off — lowest price in 2 years for this property',
    tags: ['cold', 'budget', 'culture', 'architecture', 'nightlife'],
    highlights: ['Art Nouveau building', 'Jazz bar on-site', 'Underground sauna'],
  },

  // ─── Dubrovnik ────────────────────────────────────────────────────────
  {
    id: 'dubrovnik-1',
    destination: 'Dubrovnik',
    country: 'Croatia',
    hotel: 'Hotel Excelsior',
    image: 'https://images.unsplash.com/photo-1555990538-c36c811e9b16?w=600&h=400&fit=crop',
    dates: 'May 29 – Jun 1, 2026',
    nights: 3,
    pricePerPerson: 315,
    originalPrice: 435,
    dealConfidence: 88,
    confidenceRationale: '28% below peak summer rates — book before crowds arrive',
    tags: ['warm', 'beach', 'culture', 'historic', 'romantic', 'luxury'],
    highlights: ['Old Town views', 'Private beach', 'Sea-view suites'],
  },
  {
    id: 'dubrovnik-2',
    destination: 'Dubrovnik',
    country: 'Croatia',
    hotel: 'Villa Orsula',
    image: 'https://images.unsplash.com/photo-1502786129293-79981df4e689?w=600&h=400&fit=crop',
    dates: 'Apr 24–27, 2026',
    nights: 3,
    pricePerPerson: 245,
    originalPrice: 330,
    dealConfidence: 91,
    confidenceRationale: '26% below average — pre-peak sweet spot',
    tags: ['warm', 'beach', 'romantic', 'culture', 'historic'],
    highlights: ['Cliffside location', 'Adults-only', 'Sea kayaking included'],
  },
  {
    id: 'dubrovnik-3',
    destination: 'Dubrovnik',
    country: 'Croatia',
    hotel: 'Hilton Imperial Dubrovnik',
    image: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=600&h=400&fit=crop',
    dates: 'Jun 19–22, 2026',
    nights: 3,
    pricePerPerson: 289,
    originalPrice: 420,
    dealConfidence: 76,
    confidenceRationale: 'Good price but peak season — crowds will be at maximum',
    tags: ['warm', 'beach', 'culture', 'historic', 'food'],
    highlights: ['Within Old Town walls', 'Outdoor pool', 'Award-winning restaurant'],
  },

  // ─── Marrakech ────────────────────────────────────────────────────────
  {
    id: 'marrakech-1',
    destination: 'Marrakech',
    country: 'Morocco',
    hotel: 'La Mamounia',
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&h=400&fit=crop',
    dates: 'Mar 6–9, 2026',
    nights: 3,
    pricePerPerson: 449,
    originalPrice: 620,
    dealConfidence: 86,
    confidenceRationale: '28% off — iconic hotel at a non-peak price',
    tags: ['warm', 'luxury', 'culture', 'food', 'historic', 'romantic'],
    highlights: ['Legendary palace hotel', 'World-class spa', 'Churchill\'s favourite haunt'],
  },
  {
    id: 'marrakech-2',
    destination: 'Marrakech',
    country: 'Morocco',
    hotel: 'Riad Yasmine',
    image: 'https://images.unsplash.com/photo-1539768942893-daf7b1f6823c?w=600&h=400&fit=crop',
    dates: 'Apr 3–6, 2026',
    nights: 3,
    pricePerPerson: 159,
    originalPrice: 210,
    dealConfidence: 93,
    confidenceRationale: '24% below average — authentic riad at budget price',
    tags: ['warm', 'food', 'culture', 'budget', 'historic', 'artsy'],
    highlights: ['Medina location', 'Pool and rooftop terrace', 'Traditional hammam'],
  },
  {
    id: 'marrakech-3',
    destination: 'Marrakech',
    country: 'Morocco',
    hotel: 'Royal Mansour',
    image: 'https://images.unsplash.com/photo-1531761535209-83b526e6efc6?w=600&h=400&fit=crop',
    dates: 'Feb 27 – Mar 2, 2026',
    nights: 3,
    pricePerPerson: 529,
    originalPrice: 740,
    dealConfidence: 82,
    confidenceRationale: '29% off — ultra-luxury at a relatively accessible price',
    tags: ['warm', 'luxury', 'food', 'culture', 'romantic', 'active'],
    highlights: ['Private riad suites', 'Three Michelin-starred restaurants', 'Butler service'],
  },
];
