/**
 * Seed the Supabase destinations table with rich descriptions and OpenAI embeddings.
 *
 * Usage: npx tsx scripts/seed-destinations.ts
 *
 * Requires: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, OPENAI_API_KEY
 */

import { createClient } from '@supabase/supabase-js';
import OpenAI from 'openai';
import * as fs from 'fs';
import * as path from 'path';

// Load .env.local
const envPath = path.join(__dirname, '..', '.env.local');
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx);
    const value = trimmed.slice(eqIdx + 1);
    if (!process.env[key]) process.env[key] = value;
  }
}

const DESTINATIONS = [
  {
    slug: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    iata: 'LIS',
    latitude: 38.7223,
    longitude: -9.1393,
    image_url: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800&q=80',
    tags: ['food', 'culture', 'nightlife', 'beach', 'budget'],
    seed_price_gbp: 320,
    description: 'Sun-drenched Atlantic capital known for exceptional seafood, pastéis de nata, and fado music echoing through Alfama\'s narrow lanes. Moorish architecture blends with modern street art in Mouraria. Affordable nightlife thrives in Bairro Alto\'s packed bars, while Cascais and Costa da Caparica offer easy beach escapes. The Timeout Market and Cervejaria Ramiro deliver world-class dining at reasonable prices. Tram 28 winds through historic hills past the Jerónimos Monastery and Belém Tower. A warm, walkable city that rewards slow exploration and spontaneous discovery.',
  },
  {
    slug: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    iata: 'BCN',
    latitude: 41.3874,
    longitude: 2.1686,
    image_url: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
    tags: ['food', 'architecture', 'beach', 'nightlife', 'art'],
    seed_price_gbp: 350,
    description: 'Mediterranean jewel where Gaudí\'s surreal architecture defines the skyline — from the unfinished Sagrada Família to the mosaic wonderland of Park Güell. La Boqueria market bursts with Catalan flavours, and tapas bars line the Gothic Quarter\'s medieval streets. Barceloneta beach offers urban sun-bathing steps from the city centre. The nightlife scene runs late with rooftop bars, underground clubs, and chiringuitos. World-class art museums (Picasso, Miró, MACBA) complement a thriving street art culture. Warm, vibrant, and endlessly walkable.',
  },
  {
    slug: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    iata: 'AMS',
    latitude: 52.3676,
    longitude: 4.9041,
    image_url: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80',
    tags: ['culture', 'art', 'nightlife', 'architecture'],
    seed_price_gbp: 380,
    description: 'Canal-laced capital with a golden-age heritage and forward-thinking culture. The Rijksmuseum and Van Gogh Museum house masterpieces, while the Jordaan neighbourhood offers independent galleries, vintage shops, and brown cafés. Cycling is the default transport across flat, photogenic streets. The nightlife ranges from intimate jazz clubs to massive warehouse parties. Indonesian rijsttafel and herring stands reflect centuries of global trade. A compact, bike-friendly city that blends 17th-century elegance with contemporary creativity and liberal attitudes.',
  },
  {
    slug: 'rome',
    name: 'Rome',
    country: 'Italy',
    iata: 'FCO',
    latitude: 41.9028,
    longitude: 12.4964,
    image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    tags: ['food', 'culture', 'historic', 'architecture', 'romantic'],
    seed_price_gbp: 340,
    description: 'The Eternal City layers 2,800 years of history across every piazza and cobblestone. The Colosseum, Pantheon, and Vatican draw millions, but the real magic is in Trastevere\'s trattorias serving cacio e pepe at sunset. Roman cuisine — carbonara, supplì, artichokes alla giudia — is among Italy\'s finest. Baroque fountains (Trevi, Piazza Navona) punctuate romantic evening strolls. The Borghese Gallery offers intimate encounters with Bernini and Caravaggio. Warm, chaotic, and deeply romantic — a city where every corner reveals another layer of Western civilisation.',
  },
  {
    slug: 'porto',
    name: 'Porto',
    country: 'Portugal',
    iata: 'OPO',
    latitude: 41.1579,
    longitude: -8.6291,
    image_url: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    tags: ['food', 'culture', 'budget', 'romantic'],
    seed_price_gbp: 280,
    description: 'Portugal\'s charming northern capital cascading down to the Douro River. Port wine cellars line Vila Nova de Gaia, offering tastings with panoramic river views. The Ribeira district\'s colourful waterfront is a UNESCO World Heritage Site. Francesinha sandwiches, fresh fish, and affordable Vinho Verde define the food scene. The Livraria Lello bookshop inspired Harry Potter, and azulejo-tiled churches dot every neighbourhood. More affordable and less touristy than Lisbon, with an intimate, romantic atmosphere and stunning river-valley walks across the Dom Luís I Bridge.',
  },
  {
    slug: 'prague',
    name: 'Prague',
    country: 'Czech Republic',
    iata: 'PRG',
    latitude: 50.0755,
    longitude: 14.4378,
    image_url: 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80',
    tags: ['culture', 'architecture', 'budget', 'nightlife', 'historic'],
    seed_price_gbp: 260,
    description: 'Fairytale Central European capital with Gothic, Baroque, and Art Nouveau architecture preserved across centuries. Charles Bridge at dawn, Prague Castle overlooking the Vltava, and the Astronomical Clock in Old Town Square create iconic moments. Czech beer is the world\'s best — and cheapest in any European capital. Underground clubs, jazz bars, and traditional pubs fuel vibrant nightlife. Traditional svíčková and trdelník offer hearty local flavour. One of Europe\'s most affordable capitals with an extraordinary density of architectural beauty and cultural depth.',
  },
  {
    slug: 'dubrovnik',
    name: 'Dubrovnik',
    country: 'Croatia',
    iata: 'DBV',
    latitude: 42.6507,
    longitude: 18.0944,
    image_url: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80',
    tags: ['beach', 'historic', 'romantic', 'culture'],
    seed_price_gbp: 400,
    description: 'The Pearl of the Adriatic — a walled medieval city rising from crystal-clear waters on Croatia\'s Dalmatian coast. Walking the ancient city walls offers breathtaking views of terracotta rooftops and the sparkling sea. Nearby Lokrum Island and hidden coves provide idyllic swimming spots. The Old Town\'s marble streets host atmospheric restaurants and wine bars. Game of Thrones fans recognise King\'s Landing at every turn. A romantic, historic, and strikingly beautiful destination that combines Mediterranean beach life with medieval charm and Croatian coastal cuisine.',
  },
  {
    slug: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    iata: 'RAK',
    latitude: 31.6295,
    longitude: -7.9811,
    image_url: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800&q=80',
    tags: ['food', 'culture', 'shopping', 'budget'],
    seed_price_gbp: 300,
    description: 'Sensory overload in the best way — Marrakech\'s Jemaa el-Fnaa square transforms from a daytime market to a nightly food carnival with grilled meats, fresh juices, and spice-laden tagines. The labyrinthine souks sell handcrafted leather, ceramics, and textiles at bargain prices. Hidden riads (courtyard hotels) offer oases of calm behind unassuming doors. The Majorelle Garden and Bahia Palace showcase Moroccan artistry. A budget-friendly destination where £30 buys a feast, a hammam, and mint tea. Warm year-round with a culture that invites deep, immersive exploration.',
  },
  {
    slug: 'paris',
    name: 'Paris',
    country: 'France',
    iata: 'CDG',
    latitude: 48.8566,
    longitude: 2.3522,
    image_url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    tags: ['food', 'culture', 'romantic', 'art', 'architecture', 'luxury'],
    seed_price_gbp: 400,
    description: 'The world\'s most celebrated city for romance, gastronomy, and art. From the Eiffel Tower at dusk to dawn croissants at a corner boulangerie, Paris delivers iconic moments constantly. The Louvre, Musée d\'Orsay, and Centre Pompidou hold unrivalled art collections. Michelin-starred restaurants and neighbourhood bistros serve exceptional French cuisine. Le Marais, Montmartre, and Saint-Germain each have distinct personalities for exploring. Luxury shopping on the Champs-Élysées and vintage finds in flea markets coexist. An aspirational, deeply cultural city that rewards both first-time wonder and repeat visits.',
  },
  {
    slug: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    iata: 'BER',
    latitude: 52.5200,
    longitude: 13.4050,
    image_url: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&q=80',
    tags: ['nightlife', 'art', 'culture', 'budget'],
    seed_price_gbp: 300,
    description: 'Europe\'s creative capital where history, art, and nightlife collide. The Berlin Wall\'s East Side Gallery, Checkpoint Charlie, and Holocaust Memorial tell powerful stories. Berghain and Tresor anchor a legendary techno scene that runs from Friday night to Monday morning. Street art covers entire buildings in Kreuzberg and Friedrichshain. Affordable döner kebabs, Vietnamese pho, and Michelin-starred innovation reflect its multicultural DNA. Museum Island holds world-class antiquities. Budget-friendly, edgy, and endlessly reinventing itself — Berlin is the city for creatives, night owls, and history buffs alike.',
  },
  {
    slug: 'vienna',
    name: 'Vienna',
    country: 'Austria',
    iata: 'VIE',
    latitude: 48.2082,
    longitude: 16.3738,
    image_url: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80',
    tags: ['culture', 'architecture', 'food', 'luxury', 'romantic'],
    seed_price_gbp: 340,
    description: 'Imperial grandeur meets coffeehouse culture in the city of Mozart, Klimt, and Freud. The Schönbrunn and Hofburg palaces, Vienna State Opera, and Belvedere showcase Habsburg magnificence. Traditional Viennese coffeehouses serve Sachertorte and melange in ornate 19th-century interiors. The Naschmarkt offers global street food alongside Austrian schnitzel. Classical concerts fill historic venues nightly. The MuseumsQuartier blends contemporary art with Baroque architecture. An elegant, romantic city that moves at a civilised pace — perfect for couples who love culture, music, refined food, and architectural beauty.',
  },
  {
    slug: 'budapest',
    name: 'Budapest',
    country: 'Hungary',
    iata: 'BUD',
    latitude: 47.4979,
    longitude: 19.0402,
    image_url: 'https://images.unsplash.com/photo-1551867633-194f125bddfa?w=800&q=80',
    tags: ['budget', 'nightlife', 'culture', 'architecture'],
    seed_price_gbp: 250,
    description: 'The Pearl of the Danube splits into historic Buda and lively Pest across a stunning river panorama. Thermal baths (Széchenyi, Gellért) offer relaxation in grand Art Nouveau buildings. The ruin bars of the Jewish Quarter — Szimpla Kert foremost — are Europe\'s most creative nightlife spaces. Goulash, chimney cake, and affordable Hungarian wine fuel exploration. The Parliament building, Fisherman\'s Bastion, and Chain Bridge create a photogenic skyline. One of Europe\'s best-value capitals combining thermal spa culture, ruin bar nightlife, and Danube-side grandeur at remarkably low prices.',
  },
  {
    slug: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    iata: 'CPH',
    latitude: 55.6761,
    longitude: 12.5683,
    image_url: 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800&q=80',
    tags: ['food', 'architecture', 'culture'],
    seed_price_gbp: 420,
    description: 'Scandinavian design capital and birthplace of New Nordic cuisine. Noma redefined fine dining, and its legacy lives on in dozens of innovative restaurants. Tivoli Gardens offers fairy-tale amusement in the city centre. Colourful Nyhavn harbour, the Little Mermaid, and Christiansborg Palace anchor sightseeing. Cycling culture is deeply embedded — more bikes than cars. The free town of Christiania offers an alternative commune experience. Danish hygge (cosy contentment) is a lifestyle here, from candlelit cafés to waterfront saunas. A premium destination for design lovers and gastronomes.',
  },
  {
    slug: 'athens',
    name: 'Athens',
    country: 'Greece',
    iata: 'ATH',
    latitude: 37.9838,
    longitude: 23.7275,
    image_url: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    tags: ['culture', 'historic', 'food', 'budget', 'beach'],
    seed_price_gbp: 310,
    description: 'Cradle of Western civilisation where the Acropolis and Parthenon tower over a vibrant modern city. The Ancient Agora, Temple of Olympian Zeus, and National Archaeological Museum bring millennia of history to life. Plaka\'s tavernas serve moussaka, souvlaki, and fresh Greek salads under bougainvillea-draped terraces. Rooftop bars offer Acropolis views with cocktails at sunset. Athens Riviera beaches are a short tram ride away. The Psyrrí and Exarcheia neighbourhoods pulse with street art, independent shops, and affordable nightlife. Warm, affordable, and historically profound.',
  },
  {
    slug: 'seville',
    name: 'Seville',
    country: 'Spain',
    iata: 'SVQ',
    latitude: 37.3891,
    longitude: -5.9845,
    image_url: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800&q=80',
    tags: ['food', 'culture', 'architecture', 'budget'],
    seed_price_gbp: 290,
    description: 'Andalusian capital that pulses with flamenco, tapas, and Moorish splendour. The Alcázar palace complex (a Game of Thrones location) and the world\'s largest Gothic cathedral anchor a UNESCO-rich centre. Free tapas with drinks is still a tradition in many bars. Orange tree-lined streets, the Plaza de España, and the Guadalquivir River create a warm, walkable atmosphere. Flamenco shows in Triana\'s intimate tablaos are unforgettable. Seville\'s Feria de Abril and Semana Santa are among Spain\'s greatest festivals. Budget-friendly, passionate, and architecturally stunning.',
  },
  {
    slug: 'florence',
    name: 'Florence',
    country: 'Italy',
    iata: 'FLR',
    latitude: 43.7696,
    longitude: 11.2558,
    image_url: 'https://images.unsplash.com/photo-1543429258-c5ca3e3e7b1e?w=800&q=80',
    tags: ['food', 'art', 'culture', 'architecture', 'romantic'],
    seed_price_gbp: 360,
    description: 'Renaissance jewel where Brunelleschi\'s Duomo dominates a skyline unchanged for centuries. The Uffizi Gallery holds Botticelli\'s Birth of Venus and works by Leonardo, Michelangelo, and Raphael. Tuscan cuisine — ribollita, bistecca alla fiorentina, lampredotto — is hearty and exceptional. Leather workshops in Santa Croce carry on artisan traditions. The Ponte Vecchio at golden hour is one of Europe\'s most romantic sights. Nearby Tuscan hills offer wine-tasting day trips to Chianti. A compact, walkable city that delivers world-class art, food, and romance at every turn.',
  },
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    country: 'United Kingdom',
    iata: 'EDI',
    latitude: 55.9533,
    longitude: -3.1883,
    image_url: 'https://images.unsplash.com/photo-1506377585622-bedcbb5f6eaf?w=800&q=80',
    tags: ['culture', 'historic', 'food', 'nightlife'],
    seed_price_gbp: 280,
    description: 'Scotland\'s dramatic capital split between the medieval Old Town and Georgian New Town, both UNESCO World Heritage Sites. Edinburgh Castle crowns an extinct volcano, with the Royal Mile descending to Holyrood Palace. The August Festival Fringe is the world\'s largest arts festival. Whisky bars, craft breweries, and innovative restaurants (several Michelin-starred) define the food and drink scene. Arthur\'s Seat offers a wild hike within city limits. Ghost tours, underground vaults, and literary heritage (Burns, Scott, Rowling) add mystery and depth. Atmospheric, historic, and culturally rich.',
  },
  {
    slug: 'nice',
    name: 'Nice',
    country: 'France',
    iata: 'NCE',
    latitude: 43.7102,
    longitude: 7.2620,
    image_url: 'https://images.unsplash.com/photo-1491166617655-0723a0999cfc?w=800&q=80',
    tags: ['beach', 'food', 'luxury', 'romantic'],
    seed_price_gbp: 380,
    description: 'French Riviera gem where the azure Mediterranean meets Belle Époque elegance. The Promenade des Anglais stretches along a pebbly beach backed by pastel-coloured buildings. Cours Saleya\'s flower market and Niçoise salad are local icons. The Vieille Ville (Old Town) hides socca vendors, gelaterias, and art galleries. Day trips to Monaco, Èze, and Antibes extend the luxury coastal experience. Matisse and Chagall museums celebrate the artists who loved this light. A sophisticated, sun-blessed destination for beach lovers, romantics, and those seeking Mediterranean refinement.',
  },
  {
    slug: 'split',
    name: 'Split',
    country: 'Croatia',
    iata: 'SPU',
    latitude: 43.5081,
    longitude: 16.4402,
    image_url: 'https://images.unsplash.com/photo-1555990538-1e0c3a7c8a59?w=800&q=80',
    tags: ['beach', 'historic', 'budget'],
    seed_price_gbp: 350,
    description: 'Croatia\'s second city built within and around the ruins of Diocletian\'s Roman Palace — a living monument where locals hang laundry between ancient columns. The Riva waterfront promenade buzzes with cafés and sunset views. Nearby beaches (Bačvice, Kašjuni) and islands (Hvar, Brač) offer crystalline Adriatic swimming. Fresh seafood, Croatian wine, and affordable peka (slow-cooked meat) define the food scene. The Marjan Hill park provides hiking with panoramic coastal views. A budget-friendly base for exploring the Dalmatian coast with genuine historic character and Mediterranean warmth.',
  },
  {
    slug: 'malaga',
    name: 'Malaga',
    country: 'Spain',
    iata: 'AGP',
    latitude: 36.7213,
    longitude: -4.4214,
    image_url: 'https://images.unsplash.com/photo-1564221710304-0b37c8b9d729?w=800&q=80',
    tags: ['beach', 'food', 'budget'],
    seed_price_gbp: 270,
    description: 'Costa del Sol\'s cultural capital, far beyond its beach-resort reputation. Picasso\'s birthplace hosts a dedicated museum, and the Centre Pompidou and Carmen Thyssen galleries add contemporary art depth. The Alcazaba fortress and Roman theatre reveal layers of Moorish and ancient history. Malagueta beach sits minutes from the historic centre. Espetos (grilled sardine skewers) on the beach, churros con chocolate, and bustling Atarazanas market define affordable, delicious dining. Year-round sunshine, budget flights from across Europe, and a compact walkable centre make Malaga an excellent value city break.',
  },

  // =========================================================================
  // Expanded destinations (80 more cities)
  // =========================================================================

  // --- Scandinavia & Nordics ---
  {
    slug: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    iata: 'ARN',
    latitude: 59.3293,
    longitude: 18.0686,
    image_url: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800&q=80',
    tags: ['culture', 'architecture', 'food', 'design'],
    seed_price_gbp: 400,
    description: 'Scandinavian capital spread across 14 islands connected by bridges, with a stunning old town (Gamla Stan) of cobblestone streets and ochre-coloured buildings dating to the 13th century. The Vasa Museum houses a remarkably preserved 17th-century warship. ABBA The Museum and the Nobel Prize Museum add cultural depth. New Nordic cuisine thrives here alongside traditional meatballs and herring. The archipelago offers thousands of islands for summer boat trips. Design shops, vintage stores, and craft coffee culture reflect Sweden\'s aesthetic sensibility. Elegant, clean, and effortlessly cool.',
  },
  {
    slug: 'oslo',
    name: 'Oslo',
    country: 'Norway',
    iata: 'OSL',
    latitude: 59.9139,
    longitude: 10.7522,
    image_url: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800&q=80',
    tags: ['culture', 'nature', 'architecture', 'food'],
    seed_price_gbp: 450,
    description: 'Norway\'s compact capital nestled between the Oslofjord and forested hills. The striking new Munch Museum and the National Museum anchor a world-class cultural scene. The Opera House\'s sloping marble roof invites visitors to walk up for fjord panoramas. Vigeland Sculpture Park displays over 200 works in bronze and granite. Aker Brygge and Tjuvholmen waterfronts buzz with restaurants serving fresh seafood and craft beer. Weekend trips to nearby fjords, forests, and ski slopes are effortless. A nature-loving, design-forward city that punches above its weight culturally.',
  },
  {
    slug: 'helsinki',
    name: 'Helsinki',
    country: 'Finland',
    iata: 'HEL',
    latitude: 60.1699,
    longitude: 24.9384,
    image_url: 'https://images.unsplash.com/photo-1538332576228-eb5b4c4de6f5?w=800&q=80',
    tags: ['design', 'culture', 'food', 'nature'],
    seed_price_gbp: 380,
    description: 'Finland\'s design capital on the Baltic Sea, where functionalist architecture meets cutting-edge innovation. The Oodi Central Library and Amos Rex museum showcase Finnish creativity. Authentic sauna culture — from public lakeside saunas to urban rooftop ones — is a must-experience tradition. Market Hall and Restaurant Day celebrate Nordic and global cuisine. Suomenlinna sea fortress, a UNESCO site across the harbour, offers peaceful island exploration. Helsinki\'s compact centre is walkable, with trams connecting Art Nouveau neighbourhoods, harbourside markets, and the striking Rock Church carved into granite.',
  },
  {
    slug: 'reykjavik',
    name: 'Reykjavik',
    country: 'Iceland',
    iata: 'KEF',
    latitude: 64.1466,
    longitude: -21.9426,
    image_url: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800&q=80',
    tags: ['nature', 'adventure', 'culture', 'unique'],
    seed_price_gbp: 500,
    description: 'The world\'s northernmost capital, gateway to otherworldly Icelandic landscapes — geysers, waterfalls, glaciers, and volcanic black-sand beaches. Hallgrímskirkja church dominates the colourful downtown skyline. The Blue Lagoon and Secret Lagoon offer geothermal bathing. Northern Lights in winter and midnight sun in summer create magical natural phenomena. Reykjavik\'s creative scene punches far above its size with live music, street art, and innovative restaurants serving lamb, seafood, and fermented shark. A bucket-list destination for nature lovers and adventurers seeking something truly unique.',
  },
  {
    slug: 'bergen',
    name: 'Bergen',
    country: 'Norway',
    iata: 'BGO',
    latitude: 60.3913,
    longitude: 5.3221,
    image_url: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80',
    tags: ['nature', 'historic', 'food', 'adventure'],
    seed_price_gbp: 420,
    description: 'Norway\'s fjord capital surrounded by seven mountains, with the colourful wooden houses of Bryggen Wharf (UNESCO) lining the harbour. The Fløibanen funicular ascends Mount Fløyen for breathtaking panoramic views. Bergen is the gateway to Norway in a Nutshell — fjord cruises through Sognefjord and Hardangerfjord. The fish market serves fresh king crab, smoked salmon, and whale steak. Rain-soaked but utterly charming, Bergen rewards with dramatic natural beauty, Hanseatic history, and a thriving food scene. Perfect for nature lovers who want fjord access from a walkable city.',
  },

  // --- Baltics ---
  {
    slug: 'tallinn',
    name: 'Tallinn',
    country: 'Estonia',
    iata: 'TLL',
    latitude: 59.4370,
    longitude: 24.7536,
    image_url: 'https://images.unsplash.com/photo-1560814304-4f05b62af116?w=800&q=80',
    tags: ['historic', 'budget', 'culture', 'architecture'],
    seed_price_gbp: 220,
    description: 'Estonia\'s fairy-tale capital with one of Europe\'s best-preserved medieval old towns — a UNESCO World Heritage Site of cobblestone streets, Gothic churches, and merchant houses unchanged since the 15th century. The upper town (Toompea) offers panoramic views over red rooftops to the Baltic Sea. A thriving digital culture makes it Europe\'s most tech-savvy city. Craft beer and New Nordic restaurants sit alongside medieval-themed taverns. The hipster Telliskivi Creative City hosts markets, galleries, and street food. Incredibly affordable with genuine medieval charm and modern energy.',
  },
  {
    slug: 'riga',
    name: 'Riga',
    country: 'Latvia',
    iata: 'RIX',
    latitude: 56.9496,
    longitude: 24.1052,
    image_url: 'https://images.unsplash.com/photo-1591972408689-ec47e0a21ce5?w=800&q=80',
    tags: ['architecture', 'budget', 'nightlife', 'culture'],
    seed_price_gbp: 210,
    description: 'Latvia\'s Art Nouveau jewel — over 800 ornate buildings make Riga\'s collection the finest in Europe, with elaborate facades of sphinxes, gargoyles, and floral motifs. The medieval Old Town clusters around the Dome Cathedral and Town Hall Square. Riga Central Market, housed in former Zeppelin hangars, is one of Europe\'s largest and most atmospheric. Craft cocktail bars and basement clubs fuel an energetic nightlife scene. Black balsam (herbal liqueur) and smoked fish are local signatures. One of Europe\'s most underrated and affordable capitals for architecture and nightlife lovers.',
  },
  {
    slug: 'vilnius',
    name: 'Vilnius',
    country: 'Lithuania',
    iata: 'VNO',
    latitude: 54.6872,
    longitude: 25.2797,
    image_url: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
    tags: ['historic', 'budget', 'culture', 'food'],
    seed_price_gbp: 200,
    description: 'Lithuania\'s baroque capital with Europe\'s largest surviving medieval old town (UNESCO). The self-declared Republic of Užupis — an artist quarter with its own constitution — captures Vilnius\'s creative spirit. Gediminas Tower crowns the hilltop castle complex with panoramic views. The food scene blends Lithuanian tradition (cepelinai, šaltibarščiai) with inventive modern restaurants at remarkably low prices. Hot air balloon rides over the old town are a unique local tradition. Street art, independent coffee shops, and a booming craft beer scene make Vilnius one of Europe\'s best-value creative capitals.',
  },

  // --- Eastern Europe ---
  {
    slug: 'krakow',
    name: 'Krakow',
    country: 'Poland',
    iata: 'KRK',
    latitude: 50.0647,
    longitude: 19.9450,
    image_url: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=800&q=80',
    tags: ['historic', 'culture', 'budget', 'food', 'nightlife'],
    seed_price_gbp: 230,
    description: 'Poland\'s cultural crown jewel with Europe\'s largest medieval market square (Rynek Główny), the royal Wawel Castle, and the sombre history of nearby Auschwitz. Kazimierz, the former Jewish quarter, is now Krakow\'s hippest neighbourhood — vintage bars, street art, and live jazz fill its atmospheric streets. Pierogi, żurek soup, and obwarzanek (pretzel rings) are cheap and excellent. Underground salt cathedral at Wieliczka mines amazes visitors. The nightlife rivals Berlin for intensity at a fraction of the price. A deeply historic, affordable, and endlessly fascinating city.',
  },
  {
    slug: 'warsaw',
    name: 'Warsaw',
    country: 'Poland',
    iata: 'WAW',
    latitude: 52.2297,
    longitude: 21.0122,
    image_url: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=800&q=80',
    tags: ['culture', 'historic', 'budget', 'nightlife', 'food'],
    seed_price_gbp: 240,
    description: 'Poland\'s phoenix capital, meticulously rebuilt after near-total wartime destruction. The reconstructed Old Town (UNESCO) tells a story of resilience, while the POLIN Museum chronicles 1,000 years of Jewish history. The Praga district across the Vistula buzzes with street art, neon signs, and underground bars. Milk bars (bar mleczny) serve hearty Polish meals for pennies, while new-wave restaurants earn international acclaim. Łazienki Park offers a royal palace set in beautiful gardens. A city of contrasts — devastation and beauty, tradition and innovation — at budget-friendly prices.',
  },
  {
    slug: 'bucharest',
    name: 'Bucharest',
    country: 'Romania',
    iata: 'OTP',
    latitude: 44.4268,
    longitude: 26.1025,
    image_url: 'https://images.unsplash.com/photo-1584646098378-0874589d76b1?w=800&q=80',
    tags: ['budget', 'nightlife', 'culture', 'architecture'],
    seed_price_gbp: 190,
    description: 'Romania\'s chaotic, charming capital where Belle Époque mansions sit alongside brutalist communist blocks and the absurdly vast Palace of the Parliament — the world\'s heaviest building. The Old Town\'s cobblestone streets throb with bars, clubs, and restaurants at jaw-droppingly low prices. Traditional Romanian cuisine — mici, sarmale, papanași — is hearty and delicious. The Village Museum preserves rural Romanian life in an open-air setting. Emerging as a European nightlife capital with rooftop parties and underground clubs. One of Europe\'s cheapest capitals with genuine rough-diamond charm.',
  },
  {
    slug: 'sofia',
    name: 'Sofia',
    country: 'Bulgaria',
    iata: 'SOF',
    latitude: 42.6977,
    longitude: 23.3219,
    image_url: 'https://images.unsplash.com/photo-1563178406-4cdc2923acbc?w=800&q=80',
    tags: ['budget', 'culture', 'historic', 'nature'],
    seed_price_gbp: 180,
    description: 'Bulgaria\'s underrated capital at the foot of Vitosha Mountain, layering 7,000 years of history from Roman ruins (visible in the metro) to Ottoman mosques to Soviet-era monuments. The gold-domed Alexander Nevsky Cathedral is one of Europe\'s most impressive churches. Mineral hot springs dot the city centre — free public fountains of warm thermal water. Traditional taverns (mehana) serve shopska salad, banitsa, and Bulgarian wine at extraordinarily low prices. Weekend hiking on Vitosha starts from the city limits. Europe\'s most affordable capital with surprising cultural depth and mountain access.',
  },
  {
    slug: 'belgrade',
    name: 'Belgrade',
    country: 'Serbia',
    iata: 'BEG',
    latitude: 44.7866,
    longitude: 20.4489,
    image_url: 'https://images.unsplash.com/photo-1580223530509-849e0ad4a2b6?w=800&q=80',
    tags: ['nightlife', 'budget', 'culture', 'food'],
    seed_price_gbp: 200,
    description: 'Serbia\'s raucous capital at the confluence of the Sava and Danube rivers, increasingly recognized as Europe\'s wildest nightlife destination. Splavovi (floating river clubs) host legendary parties from spring to autumn. Kalemegdan Fortress park overlooks the river confluence with 2,000 years of layered history. Skadarlija, the bohemian quarter, serves ćevapi, pljeskavica, and Serbian wine in atmospheric kafanas (taverns). Street art covers Savamala\'s warehouse district. Rakija (fruit brandy) fuels conviviality everywhere. Raw, energetic, and incredibly affordable — Belgrade is the antidote to over-polished European tourism.',
  },
  {
    slug: 'zagreb',
    name: 'Zagreb',
    country: 'Croatia',
    iata: 'ZAG',
    latitude: 45.8150,
    longitude: 15.9819,
    image_url: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80',
    tags: ['culture', 'budget', 'food', 'architecture'],
    seed_price_gbp: 230,
    description: 'Croatia\'s overlooked capital with Austro-Hungarian architecture, vibrant café culture, and none of the Dubrovnik crowds. The Upper Town\'s medieval streets cluster around St Mark\'s Church with its iconic tiled roof. Dolac Market overflows with fresh produce, cheese, and Croatian charcuterie. The Museum of Broken Relationships is brilliantly original. Tkalčićeva Street\'s bars and restaurants buzz day and night. Affordable štrukli (cheese pastry) and Croatian wines rival anything on the coast. A genuine lived-in European capital that rewards visitors who look beyond the beach-resort coastline.',
  },
  {
    slug: 'ljubljana',
    name: 'Ljubljana',
    country: 'Slovenia',
    iata: 'LJU',
    latitude: 46.0569,
    longitude: 14.5058,
    image_url: 'https://images.unsplash.com/photo-1569091791842-7cfb64e04797?w=800&q=80',
    tags: ['culture', 'nature', 'food', 'romantic', 'budget'],
    seed_price_gbp: 250,
    description: 'Slovenia\'s pocket-sized capital, a green, car-free riverside gem designed partly by Jože Plečnik. Ljubljana Castle overlooks pastel Baroque buildings reflected in the Ljubljanica River. Triple Bridge, the Dragon Bridge, and the riverside market create a walkable fairy-tale centre. Open Kitchen Friday market serves Slovenian and international street food. Lake Bled and the Julian Alps are day-trip distance. Craft beer, natural wines, and farm-to-table restaurants reflect Slovenia\'s sustainable ethos. Europe\'s Green Capital 2016 — intimate, romantic, and beautifully positioned between Alps and Adriatic.',
  },

  // --- Balkans & Southeast ---
  {
    slug: 'thessaloniki',
    name: 'Thessaloniki',
    country: 'Greece',
    iata: 'SKG',
    latitude: 40.6401,
    longitude: 22.9444,
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    tags: ['food', 'culture', 'nightlife', 'historic', 'budget'],
    seed_price_gbp: 260,
    description: 'Greece\'s second city and culinary capital, where Ottoman, Byzantine, and modern influences create an unmatched food scene. Bougatsa (custard pie), souvlaki, and meze platters along the waterfront are exceptional and cheap. The White Tower, Roman ruins, and Byzantine churches dot a walkable seafront promenade. University students fuel a late-night bar scene that rivals Athens. Modiano and Kapani markets bustle with spices, olives, and fresh fish. Less touristy and more authentically Greek than the islands — Thessaloniki is where locals eat best and stay up latest.',
  },
  {
    slug: 'istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    iata: 'IST',
    latitude: 41.0082,
    longitude: 28.9784,
    image_url: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80',
    tags: ['culture', 'food', 'historic', 'shopping', 'architecture'],
    seed_price_gbp: 280,
    description: 'The city that straddles two continents — where the Hagia Sophia, Blue Mosque, and Topkapi Palace anchor millennia of Byzantine and Ottoman grandeur. The Grand Bazaar and Spice Market offer sensory overload in the best way. Street food (simit, balık ekmek, döner) is legendary, while rooftop restaurants serve Bosphorus sunset views. Hammams provide centuries-old bathing rituals. The Asian side (Kadıköy) buzzes with local food markets and artisan coffee. A ferry ride across the Bosphorus at golden hour is one of travel\'s great experiences. Epic, affordable, and endlessly layered.',
  },
  {
    slug: 'sarajevo',
    name: 'Sarajevo',
    country: 'Bosnia and Herzegovina',
    iata: 'SJJ',
    latitude: 43.8563,
    longitude: 18.4131,
    image_url: 'https://images.unsplash.com/photo-1586791175841-4127aabcc23e?w=800&q=80',
    tags: ['historic', 'culture', 'budget', 'food'],
    seed_price_gbp: 190,
    description: 'Where East meets West in a valley ringed by mountains — Ottoman bazaars, Austro-Hungarian boulevards, and war-scarred modernist blocks tell Sarajevo\'s complex story. Baščaršija\'s copper workshops and ćevabdžinicas (grill houses) serve Bosnia\'s legendary ćevapi. The Tunnel of Hope and Srebrenica Gallery confront recent history with dignity. Bosnian coffee ritual is slower and more social than espresso culture. The surrounding mountains hosted the 1984 Winter Olympics and offer affordable skiing. Deeply moving, culturally rich, and remarkably cheap — Sarajevo transforms every visitor who makes the journey.',
  },
  {
    slug: 'tirana',
    name: 'Tirana',
    country: 'Albania',
    iata: 'TIA',
    latitude: 41.3275,
    longitude: 19.8187,
    image_url: 'https://images.unsplash.com/photo-1600022694993-f9f66ed01528?w=800&q=80',
    tags: ['budget', 'culture', 'food', 'nightlife'],
    seed_price_gbp: 170,
    description: 'Albania\'s vibrant, rapidly transforming capital — painted communist-era buildings in wild colours, buzzing Blloku district (once reserved for party elites, now packed with cafés and bars), and Ottoman-era Tanners\' Bridge. Traditional tavë kosi (lamb and yoghurt bake), byrek, and fresh Albanian wine cost almost nothing. The National History Museum and BunkArt (cold-war bunker museum) chronicle a fascinating history. Day trips to Durrës beach or Kruja castle are easy. Europe\'s most affordable emerging destination with raw energy, warm hospitality, and a food scene waiting to be discovered.',
  },
  {
    slug: 'kotor',
    name: 'Kotor',
    country: 'Montenegro',
    iata: 'TIV',
    latitude: 42.4247,
    longitude: 18.7712,
    image_url: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80',
    tags: ['historic', 'beach', 'romantic', 'nature'],
    seed_price_gbp: 300,
    description: 'A medieval walled town tucked into Europe\'s southernmost fjord — the Bay of Kotor is often called the Mediterranean\'s most dramatic setting. Venetian architecture fills the car-free old town, with churches, piazzas, and cat-filled alleyways. The 1,350-step climb to San Giovanni fortress rewards with jaw-dropping bay views. Adriatic swimming, kayaking, and boat trips to Our Lady of the Rocks island fill the days. Fresh seafood, Montenegrin wine, and waterside dining are affordable. Smaller and more intimate than Dubrovnik — a romantic, historic jewel with breathtaking natural scenery.',
  },
  {
    slug: 'mostar',
    name: 'Mostar',
    country: 'Bosnia and Herzegovina',
    iata: 'OMO',
    latitude: 43.3438,
    longitude: 17.8078,
    image_url: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800&q=80',
    tags: ['historic', 'culture', 'budget', 'architecture'],
    seed_price_gbp: 180,
    description: 'The iconic Stari Most (Old Bridge) arcs over the emerald Neretva River — rebuilt after its wartime destruction, it symbolises reconciliation and resilience. The Ottoman old town\'s cobblestone streets wind past coppersmith workshops, carpet sellers, and traditional restaurants serving Bosnian ćevapi and burek. Brave locals dive from the bridge in summer. Koski Mehmed Pasha Mosque\'s minaret offers the best view. Surrounded by Herzegovina\'s wine country and Kravice Waterfalls. A profoundly moving destination that combines Ottoman beauty, war history, and warm Bosnian hospitality at remarkably low prices.',
  },

  // --- Western Europe ---
  {
    slug: 'brussels',
    name: 'Brussels',
    country: 'Belgium',
    iata: 'BRU',
    latitude: 50.8503,
    longitude: 4.3517,
    image_url: 'https://images.unsplash.com/photo-1559113202-c916b8e44373?w=800&q=80',
    tags: ['food', 'culture', 'architecture', 'art'],
    seed_price_gbp: 300,
    description: 'Belgium\'s multilingual capital where Art Nouveau masterpieces, comic book murals, and the Grand-Place (Europe\'s most ornate square) create an architectural feast. Belgian waffles, frites, moules, and over 1,500 beers define one of the world\'s great food cultures. The Magritte Museum, Horta houses, and Atomium span centuries of creative ambition. Chocolate shops on every corner produce handmade pralines. The Marolles flea market and Saint-Géry district offer local flavour beyond the tourist trail. Underrated, affordable (for Western Europe), and gastronomically extraordinary.',
  },
  {
    slug: 'bruges',
    name: 'Bruges',
    country: 'Belgium',
    iata: 'OST',
    latitude: 51.2094,
    longitude: 3.2247,
    image_url: 'https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=800&q=80',
    tags: ['romantic', 'historic', 'food', 'architecture'],
    seed_price_gbp: 320,
    description: 'A perfectly preserved medieval city laced with canals, earning the nickname "Venice of the North." The Belfry tower, Market Square, and Church of Our Lady (housing Michelangelo\'s Madonna) anchor a compact, walkable centre. Belgian chocolate, beer, and waffles reach peak quality here. Boat rides along narrow canals pass under stone bridges and past stepped-gable houses. The Groeningemuseum holds Flemish Primitives by Van Eyck and Memling. Atmospheric, intimate, and deeply romantic — Bruges is a fairy-tale city that feels like stepping back 500 years.',
  },
  {
    slug: 'ghent',
    name: 'Ghent',
    country: 'Belgium',
    iata: 'BRU',
    latitude: 51.0543,
    longitude: 3.7174,
    image_url: 'https://images.unsplash.com/photo-1581351721010-8cf859cb14a4?w=800&q=80',
    tags: ['culture', 'food', 'architecture', 'nightlife', 'budget'],
    seed_price_gbp: 280,
    description: 'Belgium\'s best-kept secret — a student city with medieval grandeur, cutting-edge food, and none of Bruges\'s crowds. The Ghent Altarpiece (Van Eyck\'s masterwork) draws art pilgrims to St Bavo\'s Cathedral. Graslei harbour\'s guild houses create one of Europe\'s most photogenic waterfronts. Vegetarian capital of Europe with creative plant-based restaurants alongside traditional Flemish stews. The Patershol neighbourhood hides intimate restaurants in medieval lanes. A ten-day summer festival (Gentse Feesten) transforms the city into Europe\'s largest street party. More authentic and affordable than Bruges.',
  },
  {
    slug: 'luxembourg',
    name: 'Luxembourg City',
    country: 'Luxembourg',
    iata: 'LUX',
    latitude: 49.6116,
    longitude: 6.1319,
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    tags: ['culture', 'architecture', 'historic', 'luxury'],
    seed_price_gbp: 380,
    description: 'A dramatic fortress city built on cliffs above the Alzette and Pétrusse valleys, with a UNESCO-listed old town perched above deep gorges. The Bock Casemates — 17 km of underground tunnels carved into rock — are hauntingly atmospheric. The Grund district at the valley floor is filled with cafés, restaurants, and the modern MUDAM art museum. Michelin-starred restaurants and world-class wines from the Moselle Valley surprise visitors. Despite being a financial centre, Luxembourg City is compact, walkable, and strikingly beautiful. A refined weekend destination with unexpected drama.',
  },
  {
    slug: 'lyon',
    name: 'Lyon',
    country: 'France',
    iata: 'LYS',
    latitude: 45.7640,
    longitude: 4.8357,
    image_url: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&q=80',
    tags: ['food', 'culture', 'historic', 'architecture'],
    seed_price_gbp: 320,
    description: 'France\'s gastronomic capital — home to Paul Bocuse\'s legacy and more bouchons (traditional restaurants) per square kilometre than anywhere else. Quenelles, andouillette, and praline tart are local obsessions. The Presqu\'île peninsula between the Rhône and Saône rivers is a UNESCO World Heritage Site of Renaissance architecture. Traboules (secret passageways) thread through Vieux Lyon\'s silk-worker quarters. The Basilica of Notre-Dame de Fourvière crowns the hill with panoramic views. Les Halles de Lyon Paul Bocuse is a food lover\'s paradise. The serious foodie\'s alternative to Paris.',
  },
  {
    slug: 'bordeaux',
    name: 'Bordeaux',
    country: 'France',
    iata: 'BOD',
    latitude: 44.8378,
    longitude: -0.5792,
    image_url: 'https://images.unsplash.com/photo-1560983073-c29bff7438ef?w=800&q=80',
    tags: ['food', 'culture', 'architecture', 'luxury', 'romantic'],
    seed_price_gbp: 340,
    description: 'World wine capital reinvented — the Cité du Vin museum anchors a transformed waterfront along the Garonne. Classified UNESCO World Heritage for its 18th-century limestone architecture, Bordeaux\'s centre gleams after a major restoration. Saint-Émilion and Médoc wine regions are day-trip distance for tastings in legendary châteaux. Canelés, oysters from Arcachon Bay, and entrecôte à la bordelaise define the food scene. The Miroir d\'Eau reflecting pool is Europe\'s largest. More relaxed and affordable than Paris, with arguably better food and wine. A sophisticated, beautiful city for epicureans.',
  },
  {
    slug: 'marseille',
    name: 'Marseille',
    country: 'France',
    iata: 'MRS',
    latitude: 43.2965,
    longitude: 5.3698,
    image_url: 'https://images.unsplash.com/photo-1578357078586-491adf1aa5ba?w=800&q=80',
    tags: ['food', 'culture', 'beach', 'budget'],
    seed_price_gbp: 300,
    description: 'France\'s oldest city and Mediterranean melting pot — raw, diverse, and bursting with energy. The Vieux-Port fish market feeds bouillabaisse restaurants along the harbour. The Calanques National Park offers stunning limestone fjords and turquoise swimming coves minutes from the city. MuCEM (Museum of European and Mediterranean Civilisations) is architecturally striking. Le Panier, the oldest quarter, is a hillside maze of street art, artisan shops, and multicultural restaurants. Notre-Dame de la Garde basilica crowns the highest point with 360-degree views. Gritty, genuine, and increasingly fashionable.',
  },
  {
    slug: 'toulouse',
    name: 'Toulouse',
    country: 'France',
    iata: 'TLS',
    latitude: 43.6047,
    longitude: 1.4442,
    image_url: 'https://images.unsplash.com/photo-1568610864689-c5b0be80e474?w=800&q=80',
    tags: ['food', 'culture', 'budget', 'architecture'],
    seed_price_gbp: 280,
    description: 'The Pink City — named for its distinctive rose-coloured brick buildings that glow at sunset. Cassoulet (slow-cooked bean and sausage casserole) is the iconic dish, best eaten in market-side restaurants near Victor Hugo market. The Basilica of Saint-Sernin is the largest Romanesque church in Europe. Airbus factories and the Cité de l\'Espace space theme park add modern interest. The Canal du Midi (UNESCO) offers peaceful cycling and boat trips. Student energy from three universities keeps the bar and restaurant scene vibrant and affordable. France\'s most underrated major city.',
  },
  {
    slug: 'munich',
    name: 'Munich',
    country: 'Germany',
    iata: 'MUC',
    latitude: 48.1351,
    longitude: 11.5820,
    image_url: 'https://images.unsplash.com/photo-1595867818082-083862f3d630?w=800&q=80',
    tags: ['culture', 'food', 'architecture', 'nightlife'],
    seed_price_gbp: 340,
    description: 'Bavaria\'s capital where beer hall tradition meets world-class art and Alpine proximity. The Hofbräuhaus, Augustiner Keller, and English Garden beer gardens serve litres of Bavarian beer alongside weisswurst and pretzels. The Alte and Neue Pinakothek house masterpieces from Dürer to Van Gogh. Marienplatz\'s Glockenspiel chimes daily before crowds. BMW Welt and Allianz Arena add modern icons. Day trips to Neuschwanstein Castle and the Alps are effortless. Oktoberfest transforms the city annually, but Munich\'s beer garden culture thrives year-round. Prosperous, beautiful, and unapologetically Bavarian.',
  },
  {
    slug: 'hamburg',
    name: 'Hamburg',
    country: 'Germany',
    iata: 'HAM',
    latitude: 53.5511,
    longitude: 9.9937,
    image_url: 'https://images.unsplash.com/photo-1560930950-a6e90c8b2d07?w=800&q=80',
    tags: ['culture', 'nightlife', 'architecture', 'food'],
    seed_price_gbp: 300,
    description: 'Germany\'s gateway to the world — a maritime city of canals, warehouses, and the striking Elbphilharmonie concert hall rising from the harbour. The Speicherstadt warehouse district (UNESCO) is the world\'s largest contiguous warehouse complex, now home to Miniatur Wunderland and coffee roasters. The Reeperbahn in St. Pauli is legendary for nightlife — where The Beatles honed their craft. Fish Market on Sunday mornings is unmissable. HafenCity represents Europe\'s largest urban regeneration project. A creative, progressive city with maritime soul, world-class music, and serious fish sandwiches.',
  },
  {
    slug: 'cologne',
    name: 'Cologne',
    country: 'Germany',
    iata: 'CGN',
    latitude: 50.9375,
    longitude: 6.9603,
    image_url: 'https://images.unsplash.com/photo-1515091943-9d5c0ad475af?w=800&q=80',
    tags: ['culture', 'nightlife', 'architecture', 'food'],
    seed_price_gbp: 280,
    description: 'The twin-spired Cologne Cathedral (UNESCO) dominates the skyline of this 2,000-year-old Rhine city. The Belgian Quarter and Ehrenfeld neighbourhood buzz with independent shops, craft breweries, and street art. Kölsch beer is served in small glasses by surly but lovable Köbes (waiters) in traditional Brauhäuser. The Chocolate Museum and Roman-Germanic Museum span the city\'s diverse heritage. Christmas markets are among Germany\'s finest. Cologne Carnival (the "fifth season") is an explosively festive pre-Lenten celebration. Friendly, unpretentious, and culturally punchy — Germany\'s most sociable city.',
  },
  {
    slug: 'zurich',
    name: 'Zurich',
    country: 'Switzerland',
    iata: 'ZRH',
    latitude: 47.3769,
    longitude: 8.5417,
    image_url: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800&q=80',
    tags: ['luxury', 'culture', 'food', 'nature'],
    seed_price_gbp: 500,
    description: 'Switzerland\'s financial capital on the shores of Lake Zurich, backed by snow-capped Alps. The Bahnhofstrasse shopping boulevard is one of the world\'s most exclusive, while the Niederdorf old town offers medieval charm. Kunsthaus Zurich holds a major Giacometti collection. Lake swimming in summer — from Seebad Utoquai and Frauenbadi — is a beloved local ritual. Swiss cheese fondue, rösti, and Luxemburgerli (mini macarons from Sprüngli) are culinary highlights. Day trips to Lucerne, Rhine Falls, and Alpine villages are easy. Premium pricing, but the quality of life and scenery justify every franc.',
  },
  {
    slug: 'geneva',
    name: 'Geneva',
    country: 'Switzerland',
    iata: 'GVA',
    latitude: 46.2044,
    longitude: 6.1432,
    image_url: 'https://images.unsplash.com/photo-1573108037329-37aa135a142e?w=800&q=80',
    tags: ['luxury', 'culture', 'nature', 'food'],
    seed_price_gbp: 480,
    description: 'International city on the shores of Lake Geneva with the Jet d\'Eau fountain as its icon and Mont Blanc visible on clear days. The Old Town\'s winding streets lead to St Pierre Cathedral. The Red Cross Museum and UN headquarters add global significance. Swiss watchmaking heritage lives in luxury boutiques along Rue du Rhône. Lake cruises to Montreux and Lausanne offer stunning vineyard-terraced shores (Lavaux, UNESCO). Fondue, raclette, and French-influenced fine dining set against Alpine panoramas. A polished, cosmopolitan city where French sophistication meets Swiss precision.',
  },

  // --- Iberia ---
  {
    slug: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    iata: 'MAD',
    latitude: 40.4168,
    longitude: -3.7038,
    image_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80',
    tags: ['food', 'culture', 'nightlife', 'art', 'architecture'],
    seed_price_gbp: 320,
    description: 'Spain\'s grand capital where the Prado, Reina Sofía (Guernica), and Thyssen-Bornemisza form Europe\'s greatest art triangle. Tapas culture thrives in La Latina\'s Sunday Rastro market area and Malasaña\'s trendy bars. The Plaza Mayor and Royal Palace anchor a monumental city centre. Madrid\'s nightlife is legendary — dinner at 10pm, bars until 3am, clubs until dawn. Churros con chocolate at San Ginés is a 3am tradition. Retiro Park offers a central green escape with rowing boats and crystal palace. Passionate, late-night, and culturally boundless — Madrid lives at full volume.',
  },
  {
    slug: 'valencia',
    name: 'Valencia',
    country: 'Spain',
    iata: 'VLC',
    latitude: 39.4699,
    longitude: -0.3763,
    image_url: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800&q=80',
    tags: ['food', 'beach', 'architecture', 'culture', 'budget'],
    seed_price_gbp: 280,
    description: 'Birthplace of paella and home to the futuristic City of Arts and Sciences — Santiago Calatrava\'s otherworldly complex of museums, an oceanarium, and an opera house. The Turia Gardens, a 9km former riverbed park, run through the city centre for cycling and walking. Malvarrosa beach offers urban Mediterranean sun. The Central Market is one of Europe\'s largest and most beautiful, bursting with Valencian oranges, horchata, and fresh seafood. Las Fallas festival in March features giant sculptures burned in spectacular street parties. Sunny, affordable, and increasingly fashionable.',
  },
  {
    slug: 'granada',
    name: 'Granada',
    country: 'Spain',
    iata: 'GRX',
    latitude: 37.1773,
    longitude: -3.5986,
    image_url: 'https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?w=800&q=80',
    tags: ['culture', 'historic', 'food', 'budget', 'architecture'],
    seed_price_gbp: 260,
    description: 'The Alhambra palace — Europe\'s finest example of Moorish architecture — crowns this university city at the foot of the Sierra Nevada. The Albaicín quarter\'s whitewashed houses and winding streets are a UNESCO World Heritage Site, with sunset views of the Alhambra from Mirador de San Nicolás that are utterly unforgettable. Granada is one of the last Spanish cities where free tapas still come with every drink. Flamenco in the Sacromonte cave quarter is visceral and authentic. Affordable skiing in winter, Alpujarras villages in summer. Atmospheric, affordable, and architecturally transcendent.',
  },
  {
    slug: 'bilbao',
    name: 'Bilbao',
    country: 'Spain',
    iata: 'BIO',
    latitude: 43.2630,
    longitude: -2.9350,
    image_url: 'https://images.unsplash.com/photo-1567003889797-8b74d3c0d0d5?w=800&q=80',
    tags: ['food', 'art', 'architecture', 'culture'],
    seed_price_gbp: 300,
    description: 'The Guggenheim Museum Bilbao — Frank Gehry\'s titanium masterpiece — transformed this Basque industrial city into a world-class cultural destination. Jeff Koons\' giant Puppy guards the entrance. Pintxos (Basque tapas) culture is extraordinary — bar-hop through the Casco Viejo sampling miniature culinary artworks with txakoli wine. The Mercado de la Ribera is Europe\'s largest covered market. A riverside walk connects architectural landmarks from Calatrava\'s bridge to Isozaki\'s towers. The surrounding Basque Country offers rugged coastline, cider houses, and Michelin-starred restaurants. A food and art pilgrimage destination.',
  },
  {
    slug: 'san-sebastian',
    name: 'San Sebastián',
    country: 'Spain',
    iata: 'EAS',
    latitude: 43.3183,
    longitude: -1.9812,
    image_url: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80',
    tags: ['food', 'beach', 'luxury', 'culture'],
    seed_price_gbp: 380,
    description: 'The pintxos capital of the world — San Sebastián\'s Parte Vieja (old town) packs more Michelin stars per capita than anywhere on Earth. La Concha beach is consistently rated among Europe\'s finest urban beaches, a perfect crescent of golden sand. The annual film festival and jazz festival add cultural weight. Traditional cider houses (sagardotegiak) serve steak and cider poured from height. Basque cooking classes, wine tours to Rioja Alavesa, and surf culture at Zurriola beach round out the experience. An extraordinary destination for serious food lovers with beach-town beauty.',
  },
  {
    slug: 'faro',
    name: 'Faro',
    country: 'Portugal',
    iata: 'FAO',
    latitude: 37.0194,
    longitude: -7.9322,
    image_url: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    tags: ['beach', 'budget', 'nature', 'food'],
    seed_price_gbp: 250,
    description: 'Gateway to the Algarve — Portugal\'s sun-drenched southern coast with golden cliffs, sea caves, and some of Europe\'s best beaches. Faro\'s own old town is a walled enclave of cobblestone streets, a Gothic cathedral, and harbour-front cafés. The Ria Formosa lagoon system (a natural park) offers kayaking, birdwatching, and deserted island beaches. Fresh grilled fish, cataplana (seafood stew), and Algarve almonds and figs define the food scene. Benagil Cave is a boat trip away. Year-round sunshine, budget-friendly, and spectacular coastal scenery make the Algarve irresistible for beach lovers.',
  },

  // --- Mediterranean Islands ---
  {
    slug: 'palma',
    name: 'Palma de Mallorca',
    country: 'Spain',
    iata: 'PMI',
    latitude: 39.5696,
    longitude: 2.6502,
    image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
    tags: ['beach', 'food', 'architecture', 'luxury', 'culture'],
    seed_price_gbp: 340,
    description: 'Mallorca\'s capital far exceeds its package-holiday reputation — a sophisticated Mediterranean city with a Gothic cathedral (La Seu) reflected in the harbour, Joan Miró\'s studio, and a thriving contemporary art scene. The Santa Catalina neighbourhood buzzes with boutique restaurants and cocktail bars. Ensaïmada pastries, sobrassada, and pa amb oli (bread with oil and tomato) are local obsessions. Beyond the city, the Tramuntana mountains (UNESCO) offer dramatic hiking, and hidden calas (coves) provide turquoise swimming. A refined island capital that blends beach life with genuine cultural depth.',
  },
  {
    slug: 'valletta',
    name: 'Valletta',
    country: 'Malta',
    iata: 'MLA',
    latitude: 35.8989,
    longitude: 14.5146,
    image_url: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800&q=80',
    tags: ['historic', 'culture', 'beach', 'budget'],
    seed_price_gbp: 260,
    description: 'Europe\'s smallest capital and a UNESCO fortress city built by the Knights of St John, perched on a peninsula between two harbours. St John\'s Co-Cathedral houses Caravaggio\'s masterwork. The entire city is a grid of honey-coloured limestone streets with views of the Mediterranean at every turn. Pastizzi (ricotta-filled pastries) cost pennies. The Grand Harbour is one of the world\'s most spectacular, especially at sunset from the Upper Barrakka Gardens. Sister islands Gozo and Comino (Blue Lagoon) offer day trips. Warm year-round, historically extraordinary, and very affordable.',
  },
  {
    slug: 'palermo',
    name: 'Palermo',
    country: 'Italy',
    iata: 'PMO',
    latitude: 38.1157,
    longitude: 13.3615,
    image_url: 'https://images.unsplash.com/photo-1523365280197-f1783db9fe62?w=800&q=80',
    tags: ['food', 'culture', 'historic', 'budget'],
    seed_price_gbp: 260,
    description: 'Sicily\'s chaotic, magnificent capital where Arab-Norman architecture (UNESCO), crumbling palaces, and raucous street markets create sensory overload. Ballarò and Vucciria markets sell arancini, panelle (chickpea fritters), and sfincione (Sicilian pizza) for pocket change. The Palatine Chapel\'s golden Byzantine mosaics are breathtaking. The Catacombe dei Cappuccini is hauntingly unforgettable. Street food culture here rivals anywhere in the world — locals eat standing at market stalls. Mondello beach offers a suburban escape. Raw, ungentrified, and utterly authentic — Palermo is Italy at its most intense and affordable.',
  },
  {
    slug: 'naples',
    name: 'Naples',
    country: 'Italy',
    iata: 'NAP',
    latitude: 40.8518,
    longitude: 14.2681,
    image_url: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
    tags: ['food', 'culture', 'historic', 'budget'],
    seed_price_gbp: 280,
    description: 'The birthplace of pizza — Neapolitan margherita from L\'Antica Pizzeria da Michele or Sorbillo is a life-changing experience. The National Archaeological Museum holds Pompeii\'s finest treasures. The Spaccanapoli street cleaves through the historic centre (UNESCO), revealing underground Greek-Roman tunnels, Baroque churches, and electric street life. Pompeii and the Amalfi Coast are day-trip distance. Vesuvius looms over the bay. Sfogliatella pastries, espresso culture, and fresh seafood are outstanding and cheap. Naples is loud, messy, magnificent, and serves the best food in Italy — which means the best food in Europe.',
  },
  {
    slug: 'catania',
    name: 'Catania',
    country: 'Italy',
    iata: 'CTA',
    latitude: 37.5079,
    longitude: 15.0830,
    image_url: 'https://images.unsplash.com/photo-1523365280197-f1783db9fe62?w=800&q=80',
    tags: ['food', 'budget', 'beach', 'culture', 'nature'],
    seed_price_gbp: 240,
    description: 'Eastern Sicily\'s volcanic city at the foot of Mount Etna — Europe\'s tallest active volcano. Built and rebuilt from black lava stone after eruptions, Catania\'s Baroque centre (UNESCO) has dramatic dark architecture. La Pescheria fish market is one of Europe\'s most theatrical — vendors shout over pyramids of swordfish and sea urchins. Arancini, pasta alla Norma, and granita with brioche are Catanese obsessions. Etna excursions range from gentle wine-tasting to summit crater hikes. Nearby beaches include the black-sand Playa di Catania. Raw, affordable, and spectacularly located.',
  },
  {
    slug: 'cagliari',
    name: 'Cagliari',
    country: 'Italy',
    iata: 'CAG',
    latitude: 39.2238,
    longitude: 9.1217,
    image_url: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
    tags: ['beach', 'food', 'culture', 'nature', 'budget'],
    seed_price_gbp: 260,
    description: 'Sardinia\'s sun-baked capital perched on hills overlooking a vast lagoon where flamingos wade. The Castello quarter\'s medieval towers and walls offer panoramic views over terracotta rooftops to the sea. Poetto beach stretches 8km of white sand from the city centre. Sardinian cuisine — culurgiones (stuffed pasta), porceddu (suckling pig), pane frattau — is unique in Italy. The Nora archaeological site reveals Phoenician and Roman ruins on a coastal peninsula. Day trips to Costa Rei and Villasimius beaches are stunning. Mediterranean island life with genuine Italian culture and outstanding beaches.',
  },

  // --- Italy continued ---
  {
    slug: 'milan',
    name: 'Milan',
    country: 'Italy',
    iata: 'MXP',
    latitude: 45.4642,
    longitude: 9.1900,
    image_url: 'https://images.unsplash.com/photo-1520440229-6469a149ac59?w=800&q=80',
    tags: ['fashion', 'culture', 'food', 'architecture', 'luxury'],
    seed_price_gbp: 360,
    description: 'Italy\'s style capital where Leonardo\'s Last Supper, the Duomo\'s Gothic spires, and Galleria Vittorio Emanuele II\'s luxury arcade define a city of ambition and elegance. The fashion district (Quadrilatero d\'Oro) houses every major designer. Navigli canal district offers aperitivo culture — spritz and generous snack platters at sunset. Risotto alla Milanese, ossobuco, and panettone are local signatures. La Scala opera house hosts world-class performances. Brera\'s art galleries and Fondazione Prada add contemporary cultural weight. Fast-paced, fashion-forward, and culturally rich beyond its business reputation.',
  },
  {
    slug: 'venice',
    name: 'Venice',
    country: 'Italy',
    iata: 'VCE',
    latitude: 45.4408,
    longitude: 12.3155,
    image_url: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800&q=80',
    tags: ['romantic', 'culture', 'architecture', 'historic', 'art'],
    seed_price_gbp: 400,
    description: 'A floating city of 118 islands, 400 bridges, and labyrinthine canals where no cars exist — only boats, gondolas, and footsteps. St Mark\'s Basilica, the Doge\'s Palace, and the Rialto Bridge are iconic, but Venice\'s real magic is getting lost in quiet neighbourhoods like Dorsoduro and Cannaregio. The Biennale (art and architecture) draws the global creative world. Cicchetti (Venetian tapas) and spritz at canal-side bacari are essential rituals. Murano glass, Burano\'s colourful houses, and the Lido beaches extend the experience. Utterly unique, deeply romantic, and unlike anywhere else on Earth.',
  },
  {
    slug: 'bologna',
    name: 'Bologna',
    country: 'Italy',
    iata: 'BLQ',
    latitude: 44.4949,
    longitude: 11.3426,
    image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    tags: ['food', 'culture', 'architecture', 'budget'],
    seed_price_gbp: 300,
    description: 'La Grassa (The Fat One) — Italy\'s undisputed food capital. Ragù bolognese, tortellini in brodo, mortadella, and tagliatelle are born here and served with fierce local pride. The Quadrilatero market area is a foodie wonderland. Europe\'s oldest university (1088) gives Bologna perpetual youthful energy. Forty kilometres of medieval porticoes (UNESCO) shelter walkers in any weather. The Two Towers lean dramatically over the red-brick centre. Fewer tourists than Florence or Rome, better food than both, and a genuine lived-in Italian city where students and nonni share the same trattorias.',
  },
  {
    slug: 'cinque-terre',
    name: 'Cinque Terre',
    country: 'Italy',
    iata: 'GOA',
    latitude: 44.1461,
    longitude: 9.6439,
    image_url: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
    tags: ['beach', 'nature', 'romantic', 'food', 'hiking'],
    seed_price_gbp: 340,
    description: 'Five impossibly colourful fishing villages clinging to the Ligurian coast — Monterosso, Vernazza, Corniglia, Manarola, and Riomaggiore — connected by clifftop hiking trails with Mediterranean views. The Sentiero Azzurro (Blue Trail) is Italy\'s most scenic coastal walk. Pesto genovese, focaccia di Recco, fresh anchovies, and local Sciacchetrà wine define a simple, perfect food culture. Swimming from rocky coves, sunset aperitivo on harbour walls, and train-hopping between villages create an unforgettable rhythm. Car-free, stunningly beautiful, and romantic in every season. Italy\'s most Instagrammed coastline for good reason.',
  },

  // --- More Western/Central ---
  {
    slug: 'salzburg',
    name: 'Salzburg',
    country: 'Austria',
    iata: 'SZG',
    latitude: 47.8095,
    longitude: 13.0550,
    image_url: 'https://images.unsplash.com/photo-1609434601408-2ab2221e82ea?w=800&q=80',
    tags: ['culture', 'architecture', 'nature', 'romantic', 'food'],
    seed_price_gbp: 320,
    description: 'Mozart\'s birthplace and the setting for The Sound of Music — a Baroque city of churches, palaces, and fortress walls set against Alpine peaks. The Hohensalzburg Fortress crowns the old town, which is a UNESCO World Heritage Site of elaborate churches and elegant squares. The Salzburg Festival is one of the world\'s premier classical music events. Salzburger Nockerl (soufflé), Mozartkugeln (chocolate), and beer gardens in the Stiegl brewery define local flavours. The Eagle\'s Nest, Hallstatt, and the Lake District are day-trip distance. Compact, beautiful, and musically extraordinary.',
  },
  {
    slug: 'dubrovnik',
    name: 'Dubrovnik',
    country: 'Croatia',
    iata: 'DBV',
    latitude: 42.6507,
    longitude: 18.0944,
    image_url: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80',
    tags: ['beach', 'historic', 'romantic', 'culture'],
    seed_price_gbp: 400,
    description: 'The Pearl of the Adriatic — a walled medieval city rising from crystal-clear waters on Croatia\'s Dalmatian coast. Walking the ancient city walls offers breathtaking views of terracotta rooftops and the sparkling sea. Nearby Lokrum Island and hidden coves provide idyllic swimming spots. The Old Town\'s marble streets host atmospheric restaurants and wine bars. Game of Thrones fans recognise King\'s Landing at every turn. A romantic, historic, and strikingly beautiful destination that combines Mediterranean beach life with medieval charm and Croatian coastal cuisine.',
  },
  {
    slug: 'bratislava',
    name: 'Bratislava',
    country: 'Slovakia',
    iata: 'BTS',
    latitude: 48.1486,
    longitude: 17.1077,
    image_url: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80',
    tags: ['budget', 'culture', 'historic', 'nightlife'],
    seed_price_gbp: 210,
    description: 'Slovakia\'s compact Danube capital with a surprisingly charming old town of pastel Baroque buildings, quirky bronze statues, and a hilltop castle with river panoramas. Just an hour from Vienna by boat or bus, Bratislava offers similar Habsburg architecture at a fraction of the cost. Traditional bryndzové halušky (potato dumplings with sheep cheese) and Slovak beer are hearty and cheap. The UFO observation deck on the SNP Bridge offers dramatic views. A growing craft cocktail and street food scene adds modern energy. One of Europe\'s most underpriced capitals — perfect as a Vienna day trip or weekend base.',
  },
  {
    slug: 'porto-montenegro',
    name: 'Podgorica',
    country: 'Montenegro',
    iata: 'TGD',
    latitude: 42.4304,
    longitude: 19.2594,
    image_url: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80',
    tags: ['nature', 'budget', 'adventure', 'culture'],
    seed_price_gbp: 200,
    description: 'Montenegro\'s small capital serves as the gateway to the country\'s extraordinary natural beauty — Durmitor National Park, Tara River Canyon (Europe\'s deepest), and Lake Skadar. The city itself is an unpretentious mix of Ottoman and Austro-Hungarian remnants with a buzzing café culture along the Morača River. Njeguški steak, Balkan grill, and excellent Montenegrin wines (especially Vranac) are affordable and delicious. Day trips to Ostrog Monastery (built into a cliff face) and the Adriatic coast are easy. A launching pad for nature adventures in one of Europe\'s most underexplored countries.',
  },

  // --- Greece & Cyprus ---
  {
    slug: 'crete',
    name: 'Heraklion (Crete)',
    country: 'Greece',
    iata: 'HER',
    latitude: 35.3387,
    longitude: 25.1442,
    image_url: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    tags: ['beach', 'food', 'culture', 'historic', 'nature'],
    seed_price_gbp: 280,
    description: 'Greece\'s largest island and the cradle of Minoan civilisation — Knossos Palace dates to 1700 BC. Heraklion\'s Venetian harbour, fortress, and archaeological museum anchor the capital. Cretan cuisine is considered Greece\'s healthiest and most flavourful — dakos, kalitsounia, and lamb with stamnagathi (wild greens) alongside local olive oil and raki. Pink-sand Elafonisi beach and the Samaria Gorge hike are bucket-list natural wonders. Rethymno and Chania offer photogenic Venetian-Ottoman harbour towns. Warm well into autumn, culturally rich, and gastronomically superior — Crete is Greece at its most complete.',
  },
  {
    slug: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    iata: 'JTR',
    latitude: 36.3932,
    longitude: 25.4615,
    image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    tags: ['romantic', 'beach', 'luxury', 'food'],
    seed_price_gbp: 420,
    description: 'The volcanic caldera island that defines Greek island romance — whitewashed houses with blue domes cascade down cliffs above the Aegean. Oia\'s sunset is one of the world\'s most famous. Black and red volcanic beaches (Perissa, Red Beach) offer unique swimming. Assyrtiko wine from volcanic vineyards is world-class and produced nowhere else. Cherry tomatoes, fava, and fresh seafood define a distinctive local cuisine. Boat trips to the volcanic hot springs and Thirassia island extend the experience. Premium pricing but absolutely unforgettable — the ultimate romantic Mediterranean escape.',
  },
  {
    slug: 'corfu',
    name: 'Corfu',
    country: 'Greece',
    iata: 'CFU',
    latitude: 39.6243,
    longitude: 19.9217,
    image_url: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    tags: ['beach', 'culture', 'romantic', 'nature', 'food'],
    seed_price_gbp: 300,
    description: 'The greenest Greek island — lush with olive groves, cypress trees, and Venetian, French, and British colonial architecture unique in Greece. Corfu Town\'s Liston arcade and Spianada square echo Parisian elegance. The Old Fortress and New Fortress frame a UNESCO World Heritage old town of narrow kantounia (alleys). Paleokastritsa\'s turquoise bays and Canal d\'Amour at Sidari offer stunning swimming. Sofrito, pastitsada, and kumquat liqueur are Corfiot signatures. Gerald Durrell\'s beloved island retains its charm beyond the resorts. A romantic, culturally rich island with Venetian soul and Greek warmth.',
  },
  {
    slug: 'rhodes',
    name: 'Rhodes',
    country: 'Greece',
    iata: 'RHO',
    latitude: 36.4341,
    longitude: 28.2176,
    image_url: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    tags: ['beach', 'historic', 'culture', 'budget'],
    seed_price_gbp: 270,
    description: 'The largest Dodecanese island with a spectacularly preserved medieval old town (UNESCO) — the Street of the Knights and Palace of the Grand Master transport visitors to the Crusader era. Ancient Lindos perches on a cliff above a perfect bay. Over 300 days of sunshine make Rhodes one of Europe\'s sunniest destinations. Prasonisi at the southern tip is a world-class windsurfing spot. Traditional tavernas serve fresh fish, meze, and local Athiri wine at reasonable prices. The Valley of the Butterflies and ancient Kamiros ruins add natural and historical depth. Sun-drenched history and beach perfection.',
  },
  {
    slug: 'larnaca',
    name: 'Larnaca',
    country: 'Cyprus',
    iata: 'LCA',
    latitude: 34.9003,
    longitude: 33.6232,
    image_url: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80',
    tags: ['beach', 'culture', 'food', 'budget'],
    seed_price_gbp: 280,
    description: 'Cyprus\'s laid-back coastal city with a palm-lined seafront promenade, Finikoudes beach, and a medieval fort guarding the harbour. The Church of Saint Lazarus is one of Christianity\'s most significant. Cypriot meze — halloumi, souvlaki, koupepia, sheftalia — is a feast of 20+ small dishes shared communally. The salt lake hosts flamingos in winter. Larnaca serves as a gateway to the Troodos Mountains, ancient Kourion, and the Akamas Peninsula. British colonial heritage blends with Greek Cypriot warmth. Year-round sunshine, affordable Mediterranean living, and genuine Cypriot hospitality define this understated coastal city.',
  },

  // --- UK & Ireland ---
  {
    slug: 'dublin',
    name: 'Dublin',
    country: 'Ireland',
    iata: 'DUB',
    latitude: 53.3498,
    longitude: -6.2603,
    image_url: 'https://images.unsplash.com/photo-1549918864-48ac978761a4?w=800&q=80',
    tags: ['culture', 'nightlife', 'food', 'historic'],
    seed_price_gbp: 320,
    description: 'Ireland\'s literary capital — home to Joyce, Wilde, Yeats, and Beckett — with the Book of Kells at Trinity College and a thriving contemporary writing scene. Temple Bar\'s cobblestone streets pulse with live music, traditional pubs, and craft beer bars. The Guinness Storehouse and Jameson Distillery are pilgrimage sites. Dublin\'s food scene has evolved dramatically — Michelin-starred restaurants alongside traditional coddle and boxty. The Howth cliff walk and Killiney Bay offer coastal escapes. Craic (fun, conversation, music) is the city\'s currency — warm, witty, and deeply hospitable.',
  },
  {
    slug: 'glasgow',
    name: 'Glasgow',
    country: 'United Kingdom',
    iata: 'GLA',
    latitude: 55.8642,
    longitude: -4.2518,
    image_url: 'https://images.unsplash.com/photo-1506377585622-bedcbb5f6eaf?w=800&q=80',
    tags: ['culture', 'nightlife', 'art', 'food', 'budget'],
    seed_price_gbp: 240,
    description: 'Scotland\'s largest city with a fiercely creative spirit — Charles Rennie Mackintosh\'s Art Nouveau buildings, the Kelvingrove Art Gallery, and a legendary live music scene (King Tut\'s, Barrowlands) define Glasgow\'s cultural identity. The West End\'s Ashton Lane and Finnieston\'s restaurants (the "Finieston strip") offer Scotland\'s best dining outside Edinburgh. Street art, independent galleries, and the Barras flea market add grit and character. Glaswegians are famously friendly and funny. More affordable than Edinburgh with arguably better nightlife, food, and atmosphere. A no-nonsense, big-hearted creative city.',
  },

  // --- More destinations ---
  {
    slug: 'sorrento',
    name: 'Sorrento',
    country: 'Italy',
    iata: 'NAP',
    latitude: 40.6263,
    longitude: 14.3758,
    image_url: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
    tags: ['romantic', 'food', 'beach', 'culture', 'luxury'],
    seed_price_gbp: 360,
    description: 'Clifftop town overlooking the Bay of Naples with Vesuvius across the water — the gateway to the Amalfi Coast, Capri, and Pompeii. Lemon groves scent the air and produce limoncello, lemon granita, and lemon-everything. Marina Grande\'s fishing village atmosphere and Piazza Tasso\'s evening passeggiata create old-world Italian charm. Gnocchi alla sorrentina is the signature dish. Ferries to Capri, Positano, and Amalfi depart from the harbour. Dramatic cliff walks connect to neighbouring villages. A romantic base for exploring Campania\'s greatest hits — equal parts dolce vita and natural spectacle.',
  },
  {
    slug: 'antalya',
    name: 'Antalya',
    country: 'Turkey',
    iata: 'AYT',
    latitude: 36.8969,
    longitude: 30.7133,
    image_url: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80',
    tags: ['beach', 'historic', 'budget', 'nature', 'food'],
    seed_price_gbp: 220,
    description: 'Turkey\'s Mediterranean resort capital with a beautifully preserved old town (Kaleiçi) of Ottoman mansions, Roman ruins, and harbour-front restaurants. Konyaaltı and Lara beaches stretch for kilometres backed by the Taurus Mountains. The Antalya Museum houses one of Turkey\'s finest archaeological collections. Ancient cities Perge, Aspendos (with its intact Roman theatre), and Termessos are day-trip distance. Fresh fish, meze, kebabs, and Turkish breakfast are outstanding and cheap. The Düden Waterfalls cascade directly into the sea. Year-round warmth, extraordinary history, and genuine Turkish hospitality at rock-bottom prices.',
  },
  {
    slug: 'gdansk',
    name: 'Gdansk',
    country: 'Poland',
    iata: 'GDN',
    latitude: 54.3520,
    longitude: 18.6466,
    image_url: 'https://images.unsplash.com/photo-1560814304-4f05b62af116?w=800&q=80',
    tags: ['historic', 'culture', 'budget', 'beach', 'food'],
    seed_price_gbp: 230,
    description: 'Poland\'s Baltic port city with a meticulously reconstructed old town of colourful Hanseatic merchant houses along the Motława River. Długi Targ (Long Market) and the Neptune Fountain create a fairy-tale main street. The European Solidarity Centre tells the story of the Solidarity movement that helped end communism. Sopot\'s sandy beach and longest wooden pier in Europe are a tram ride away. Amber jewellery, craft beer, and pierogi are local obsessions. The WWII Museum is one of Europe\'s most powerful. Historic, atmospheric, and affordable — Gdansk is Poland\'s most attractive coastal city.',
  },
  {
    slug: 'dubrovnik',
    name: 'Dubrovnik',
    country: 'Croatia',
    iata: 'DBV',
    latitude: 42.6507,
    longitude: 18.0944,
    image_url: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80',
    tags: ['beach', 'historic', 'romantic', 'culture'],
    seed_price_gbp: 400,
    description: 'The Pearl of the Adriatic — a walled medieval city rising from crystal-clear waters on Croatia\'s Dalmatian coast. Walking the ancient city walls offers breathtaking views of terracotta rooftops and the sparkling sea. Nearby Lokrum Island and hidden coves provide idyllic swimming spots. The Old Town\'s marble streets host atmospheric restaurants and wine bars. Game of Thrones fans recognise King\'s Landing at every turn. A romantic, historic, and strikingly beautiful destination that combines Mediterranean beach life with medieval charm and Croatian coastal cuisine.',
  },
  {
    slug: 'zadar',
    name: 'Zadar',
    country: 'Croatia',
    iata: 'ZAD',
    latitude: 44.1194,
    longitude: 15.2314,
    image_url: 'https://images.unsplash.com/photo-1555990538-1e0c3a7c8a59?w=800&q=80',
    tags: ['beach', 'historic', 'culture', 'budget'],
    seed_price_gbp: 270,
    description: 'Croatia\'s most underrated coastal city — the Sea Organ plays haunting music from wave energy, and the Sun Salutation lights up the harbour at sunset (Alfred Hitchcock called it the world\'s most beautiful). Roman ruins, Venetian fortifications, and medieval churches fill a walkable peninsula old town. Nearby Plitvice Lakes National Park is Croatia\'s natural crown jewel. Pag Island\'s cheese, Maraschino liqueur (invented here), and fresh Adriatic seafood define the food scene. Kornati Islands National Park offers pristine sailing. Less crowded and cheaper than Dubrovnik with equal coastal beauty and more natural wonders.',
  },
  {
    slug: 'porto-santo',
    name: 'Funchal (Madeira)',
    country: 'Portugal',
    iata: 'FNC',
    latitude: 32.6669,
    longitude: -16.9241,
    image_url: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    tags: ['nature', 'food', 'adventure', 'beach', 'romantic'],
    seed_price_gbp: 300,
    description: 'Madeira\'s subtropical island capital — the "floating garden of the Atlantic" with year-round mild weather, dramatic volcanic landscapes, and levada walks through ancient laurel forests (UNESCO). Funchal\'s Mercado dos Lavradores overflows with exotic fruits (banana, passion fruit, custard apple). Espetada (beef skewers on laurel sticks) and bolo do caco (garlic bread) are local signatures. The toboggan ride from Monte is uniquely thrilling. Natural volcanic swimming pools at Porto Moniz sit at the island\'s edge. Madeira wine cellars and quinta gardens add cultural depth. An island paradise for hikers, nature lovers, and food enthusiasts.',
  },
];

async function main() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const openaiKey = process.env.OPENAI_API_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
    process.exit(1);
  }
  if (!openaiKey) {
    console.error('Missing OPENAI_API_KEY');
    process.exit(1);
  }

  const supabase = createClient(supabaseUrl, supabaseKey);
  const openai = new OpenAI({ apiKey: openaiKey });

  console.log(`Seeding ${DESTINATIONS.length} destinations...`);

  for (const dest of DESTINATIONS) {
    console.log(`  ${dest.name}: generating embedding...`);

    const embeddingResponse = await openai.embeddings.create({
      model: 'text-embedding-3-small',
      input: dest.description,
    });
    const embedding = embeddingResponse.data[0].embedding;

    const { error } = await supabase.from('destinations').upsert(
      {
        slug: dest.slug,
        name: dest.name,
        country: dest.country,
        iata: dest.iata,
        latitude: dest.latitude,
        longitude: dest.longitude,
        image_url: dest.image_url,
        description: dest.description,
        tags: dest.tags,
        seed_price_gbp: dest.seed_price_gbp,
        embedding: JSON.stringify(embedding),
        updated_at: new Date().toISOString(),
      },
      { onConflict: 'slug' }
    );

    if (error) {
      console.error(`  ERROR upserting ${dest.name}:`, error.message);
    } else {
      console.log(`  ${dest.name}: done (${embedding.length} dimensions)`);
    }
  }

  console.log('Seeding complete!');
}

main().catch((err) => {
  console.error('Seed script failed:', err);
  process.exit(1);
});
